- package-lock.json
- package.json
- src/setupTests.ts
`@testing-library/react` react contains some dependencies that are WTFPL licensed. 
license-checker output:
```
├─ MIT: 1256
├─ ISC: 101
├─ BSD-3-Clause: 36
├─ BSD-2-Clause: 34
├─ Apache-2.0: 32
├─ CC0-1.0: 28
├─ (MIT OR CC0-1.0): 5
├─ 0BSD: 2
├─ (MIT OR Apache-2.0): 1
├─ MPL-2.0: 1
├─ CC-BY-4.0: 1
├─ BSD: 1
├─ UNLICENSED: 1
├─ (Apache-2.0 OR MPL-1.1): 1
├─ AFLv2.1,BSD: 1
├─ ODC-By-1.0: 1
├─ (BSD-3-Clause OR GPL-2.0): 1
├─ (MIT AND Zlib): 1
├─ (WTFPL OR MIT): 1
├─ MIT*: 1
├─ (MIT AND BSD-3-Clause): 1
├─ CC-BY-3.0: 1
└─ Unlicense: 1
```
closes #1
> remove @testing-library/* dependencies

- public/index.html
- public/manifest.json
- src/components/DataTable/DataTable.tsx
- src/components/DataTable/DataTableRow.tsx
- src/interfaces.ts
- src/translations/en.json
- src/views/Dashboard.tsx
- messages/transactions count
- placeholder network members
- latest messages table
- updated title to "Firefly Explorer"
Graphs will be added in a future PR
closes #7
> explorer dashboard

- src/App.tsx
- src/components/HashPopover.tsx
- src/components/MessageDetails.tsx
- src/views/Dashboard.tsx
- src/views/Data.tsx
- src/views/Messages.tsx
- renamed AddressPopover to HashPopover
> Base data view

- public/index.html
- src/App.tsx
Signed-off-by: Nicko Guyer <nicko.guyer@kaleido.io>
> Update routing to be served from firefly core

- src/App.tsx
- src/components/MessageDetails.tsx
- src/components/StatusChip.tsx
- src/interfaces.ts
- src/translations/en.json
- src/views/Messages.tsx
- src/views/Transactions/TransactionDetails.tsx
- src/views/Transactions/Transactions.tsx
View more in-depth tx info by clicking on an item in the transaction table.
- add linking to tx details from message details pane via `View TX` button
> Transaction details view

- package-lock.json
- package.json
- src/components/RecentTransactions/RecentTransactions.tsx
- src/components/RecentTransactions/TransactionPieChart.tsx
- src/interfaces.ts
- src/translations/en.json
- src/views/Dashboard.tsx
Recent transactions pie chart, currently shows transactions within the last 24 hours
> recent transactions dashboard chart

- .eslintrc.js
- README.md
- public/index.html
- public/manifest.json
- src/App.tsx
- src/components/DataTimeline/DataTimeline.tsx
- src/components/DataTimeline/TimelineItemWrapper.tsx
- src/components/DataTimeline/TimelineItems/OppositeTimelineItem.tsx
- src/components/DataTimeline/TimelineItems/TimelineContentPanel.tsx
- src/components/DataTimeline/TimelineItems/TimelineItem.tsx
- src/components/DataViewSwitch.tsx
- src/components/FilterSelect.tsx
- src/components/Navigation/Navigation.tsx
- src/contexts/ApplicationContext.tsx
- src/expanded-theme.ts
- src/interfaces.ts
- src/translations/en.json
- src/views/Dashboard.tsx
- src/views/Data.tsx
- src/views/Messages/MessageDetails.tsx
- src/views/Messages/Messages.tsx
- src/views/Transactions/Transactions.tsx
- default is 24 hours
- options include 24 hours, 7 days, 30 days
includes changes from #16
> add created time filter for tx, messages, data

- src/interfaces.ts
- src/views/Dashboard.tsx
The current org API does not return a count, so this will return the current org count up to 100
> adding org count to dashboard

- src/App.tsx
- now using secondary text color
> override color of select hover/focus

- package-lock.json
- package.json
- src/App.tsx
- src/components/DataTimeline/DataTimeline.tsx
- src/components/RecentTransactions/RecentTransactions.tsx
- src/contexts/ApplicationContext.tsx
- src/index.tsx
- src/interfaces.ts
- src/translations/en.json
- src/views/Dashboard.tsx
- src/views/Data.tsx
- src/views/Messages/MessageDetails.tsx
- src/views/Messages/Messages.tsx
- src/views/Transactions/TransactionDetails.tsx
- src/views/Transactions/Transactions.tsx
- auto refresh views when new events are received
- update transaction status types
- update view & interfaces to match latest API spec
> websocket integration

- src/views/Dashboard.tsx
No longer rely on sequence numbers for total counts across namespaces.
For now (a hack) while a count API is being developed, just set a high limit on dashboard queries and add a time filter.
> add message & data counts to dashboard

- package-lock.json
- package.json
- src/App.tsx
- src/components/DataTimeline/DataTimeline.tsx
- src/components/DataTimeline/TimelineItems/TimelineContentPanel.tsx
- src/components/DataTimeline/TimelineItems/TimelineItem.tsx
- src/contexts/ApplicationContext.tsx
- src/interfaces.ts
- src/translations/en.json
- src/views/Data.tsx
- src/views/Data/Data.tsx
- src/views/Data/DataDetails.tsx
- src/views/Messages/MessageDetails.tsx
- src/views/Messages/Messages.tsx
- src/views/Transactions/Transactions.tsx
- Display data values in message details
- Added new data details view, which displays the value of a data item.
in chain with #34
> add data values to message & data details view

- src/App.tsx
- src/components/DataTimeline/DataTimeline.tsx
- src/components/DataTimeline/TimelineItems/TimelineContentPanel.tsx
- src/components/DataTimeline/TimelineItems/TimelineItem.tsx
- src/contexts/ApplicationContext.tsx
- src/interfaces.ts
- src/views/Data.tsx
- src/views/Messages/Messages.tsx
- src/views/Transactions/Transactions.tsx
- "our" organization is now displayed on the left in the timeline
- remove timeline from data view
> filter timelines by organization

- .eslintrc.js
- .github/workflows/build.yml
- .github/workflows/release.yml
- package-lock.json
- package.json
- src/App.tsx
PR build is tested. I don't think I can test the tag release extensions without it being in the build
> Add github actions for PRs and Releases

- package.json
- src/components/DataTimeline/TimelineItems/TimelineContentPanel.tsx
- src/views/Dashboard.tsx
- src/views/Data/Data.tsx
- src/views/Messages/Messages.tsx
- src/views/Transactions/TransactionDetails.tsx
- src/views/Transactions/Transactions.tsx
Also set maxWidth on views for better appearance on higher resolutions
> improve timeline appearance on smaller resolutions

- src/utils.ts
Omit extra slash, resource already contains slash
> Bug in request URL

- CHANGELOG.md
- CODEOWNERS
- CONTRIBUTING.md
- LICENSE
- MAINTAINERS.md
Signed-off-by: Nicko Guyer <nicko.guyer@kaleido.io>
> Add files for consistent repo structure

- package-lock.json
- package.json
- src/components/DataTimeline/DataTimeline.tsx
- src/components/DataViewSwitch.tsx
- src/components/RecentTransactions/RecentTransactions.tsx
- src/components/RecentTransactions/TransactionPieChart.tsx
- src/components/Routes.tsx
- src/hooks/useIntersectionObserver.ts
- src/interfaces.ts
- src/translations/en.json
- src/views/Dashboard.tsx
- src/views/Transactions/TransactionList.tsx
- src/views/Transactions/TransactionTimeline.tsx
- src/views/Transactions/Transactions.tsx
Increases responsiveness & appearance on smaller screens
> Hide transaction pie chart center label on small screens 

- package-lock.json
- package.json
- src/components/DataTimeline/DataTimeline.tsx
- src/components/DataViewSwitch.tsx
- src/components/RecentTransactions/RecentTransactions.tsx
- src/components/Routes.tsx
- src/hooks/useIntersectionObserver.ts
- src/interfaces.ts
- src/translations/en.json
- src/views/Dashboard.tsx
- src/views/Transactions/TransactionList.tsx
- src/views/Transactions/TransactionTimeline.tsx
- src/views/Transactions/Transactions.tsx
- Message & Transaction timeline view now supports infinite scrolling
- Timeline is now the default view
- WebSocket event updates do not move the user from where they are scrolled on the timeline
Also changed dashboard transaction pie chart to show the 50 most recent transactions and changed the title to "Recent Transactions".
closes #17
> Timeline Infinite Scroll

- CONTRIBUTING.md
Signed-off-by: Nicko Guyer <nicko.guyer@kaleido.io>
> Remove references to labs

- README.md
Signed-off-by: srishti <srishti@havenlife.com>
> resolves #62

- package.json
- src/core/App.tsx
- src/core/components/DatePicker.tsx
- src/core/components/FilterDisplay.tsx
- src/core/components/FilterModal.tsx
- src/core/components/FilterSelect.tsx
- src/core/translations/en.json
- src/core/utils.ts
- src/modules/data/translations/en.json
- src/modules/data/views/Dashboard.tsx
- src/modules/data/views/Data/Data.tsx
- src/modules/data/views/Messages/MessageList.tsx
- src/modules/data/views/Messages/MessageTimeline.tsx
- src/modules/data/views/Messages/Messages.tsx
- src/modules/data/views/Transactions/TransactionList.tsx
- src/modules/data/views/Transactions/TransactionTimeline.tsx
- src/modules/data/views/Transactions/Transactions.tsx
This PR adds enhanced filtering for the message, data, and transactions views of the data module.
* Introduces a new modal for selecting the `field`, `operator`, and `value` of the filter
* A display bar to manage your active filters
* Filters stored as query params for easy linking & sharing
closes #47 
Update: adjusted select border color and filter button height
> [Data Explorer]: Message, Data, and Transaction Filtering

- src/core/interfaces.ts
- src/core/utils.ts
- src/modules/home/translations/en.json
- src/modules/home/views/Home.tsx
- src/modules/tokens/registration.ts
- src/modules/tokens/translations/en.json
- src/modules/tokens/views/Accounts/AccountDetails.tsx
- src/modules/tokens/views/Accounts/Accounts.tsx
- src/modules/tokens/views/Dashboard.tsx
- src/modules/tokens/views/TokenPools/TokenPools.tsx
- src/modules/tokens/views/Transfers/TransferDetails.tsx
- src/modules/tokens/views/Transfers/Transfers.tsx
> Fix token accounts to align with latest APIs

- package.json
- src/modules/tokens/views/Dashboard.tsx
depends on https://github.com/hyperledger/firefly/pull/319
> use count query param for token accounts

- src/modules/home/translations/en.json
- src/modules/home/views/Home.tsx
- module links now include namespace
closes #76
> add tokens i18n, fix home page module links

- src/core/interfaces.ts
- src/modules/tokens/translations/en.json
- src/modules/tokens/views/Accounts/AccountDetails.tsx
- src/modules/tokens/views/Transfers/TransferDetails.tsx
- src/modules/tokens/views/Transfers/Transfers.tsx
Depends on https://github.com/hyperledger/firefly/pull/335
> Add token URI, clean up token transfer message ID

- package.json
Signed-off-by: Alex Shorsher <alex.shorsher@kaleido.io>
> version 0.4.3

- src/modules/tokens/views/Accounts/Accounts.tsx
- src/modules/tokens/views/TokenPools/TokenPools.tsx
- src/modules/tokens/views/Transfers/Transfers.tsx
Filtering for 
* Accounts
* Pools
* Transfers
> Tokens filtering

- src/core/interfaces.ts
- src/modules/data/translations/en.json
- src/modules/data/views/Data/Data.tsx
- also removes ability to show data details if there is no data value
> add blob name, size, and download icon to data

- src/App.tsx
> [v1] linting

- src/components/Cards/EmptyStateCard.tsx
- src/components/Cards/EventCards/SkeletonCard.tsx
- src/components/Tables/Table.tsx
- src/components/Tables/TableEmptyState.tsx
- src/components/Tables/TableRowSkeleton.tsx
- src/pages/Blockchain/views/Dashboard.tsx
- src/pages/Blockchain/views/Events.tsx
- src/pages/Home/views/Dashboard.tsx
- src/pages/Off-Chain/views/Dashboard.tsx
- src/pages/Tokens/views/Dashboard.tsx
- src/utils/filters.ts
- Loading states with skeleton text for better ui experience
> [loading-states] loading state for tables and cards

- src/App.tsx
- src/components/Header.tsx
- src/components/Navigation/Navigation.tsx
- src/components/Router.tsx
- src/components/Timeline/FFTimeline.tsx
- src/pages/Activity/views/Operations.tsx
- src/translations/en.json
> [ui-routing] adding basename to routing

- src/components/Accordions/BlockchainEventAccordion.tsx
- src/components/Accordions/MessageAccordion.tsx
- src/components/Accordions/OperationAccordion.tsx
- src/components/Buttons/MsgButton.tsx
- src/components/Lists/MessageList.tsx
- src/components/Lists/OperationList.tsx
- src/components/Lists/TransferList.tsx
- src/components/NetworkMap/NetworkMap.tsx
- src/components/Tables/Table.tsx
- src/components/Viewers/FFJsonViewer.tsx
- src/interfaces/enums/eventTypes.ts
- src/pages/Activity/views/Operations.tsx
- src/pages/Off-Chain/views/Dashboard.tsx
- src/pages/Off-Chain/views/Messages.tsx
- src/translations/en.json
> [ui-tweaks] network map, json viewer, status chips

- src/components/Router.tsx
> [nav-bug] using routeAdapter

- src/components/Navigation/Navigation.tsx
- src/pages/MyNode/views/Subscriptions.tsx
> [linting] linting

- src/components/Cards/SmallCard.tsx
- src/components/Lists/BalanceList.tsx
- src/components/NetworkMap/NetworkMap.tsx
> [misc-tweaks] removing unneeded width params

- src/components/Accordions/DataViewerAccordion.tsx
- src/components/Accordions/MessageDataAccordion.tsx
- src/components/Slides/DataSlide.tsx
- src/components/Viewers/FFJsonViewer.tsx
- src/translations/en.json
- Adds new accordion for FF data objects
- Changes react-json-view theme
> Data View Accordion

- src/components/AppWrapper.tsx
- set `replace: true` when updating search params
> fix browser back button

- src/components/Cards/FireFlyCard.tsx
- src/pages/Home/views/Dashboard.tsx
> [alignment] home dashboard recent events vertical scroll

- src/components/Cards/EventCards/BaseCard.tsx
- src/components/Cards/FireFlyCard.tsx
- src/components/Charts/Histogram.tsx
- src/components/NetworkMap/NetworkMap.tsx
- src/interfaces/filters.ts
- src/pages/MyNode/views/Dashboard.tsx
- src/pages/Tokens/views/PoolDetails.tsx
- src/theme.tsx
- Pool details page spacing
- Filter update
- Scrollbar theme
- Responsiveness
> Minor cosmetics

- src/components/Cards/EventCards/EventCardWrapper.tsx
- src/components/Cards/FireFlyCard.tsx
- src/pages/Activity/views/Timeline.tsx
- src/pages/Home/views/Dashboard.tsx
- src/theme.tsx
- Fixes button click but in timeline view
- Alternate scrollbar theming
> Timeline btn bug

- src/components/Lists/BatchList.tsx
- src/components/Lists/MessageList.tsx
- src/interfaces/api.ts
- src/interfaces/navigation.ts
https://user-images.githubusercontent.com/17093033/165621951-78a7856c-ff6c-4d47-babc-aa3b4195916c.mov
>
> [group-hash] group hashes to batch and message tables

- package.json
- src/pages/Off-Chain/views/Data.tsx
Signed-off-by: Gabriel Indik <gabriel.indik@kaleido.io>
> Format sizes in data view

- src/interfaces/navigation.ts
- src/pages/Tokens/views/Dashboard.tsx
https://user-images.githubusercontent.com/17093033/165977647-2a03c5da-d63f-4647-8e30-7c07898dbcee.mov
>
> [pool-error-path] error in pool card links to correct page

- src/App.tsx
- src/components/NetworkMap/NetworkMap.tsx
- src/interfaces/api.ts
- src/pages/Network/views/Dashboard.tsx
- src/pages/Network/views/Nodes.tsx
- src/pages/Network/views/Organizations.tsx
Update UI to work with changes from https://github.com/hyperledger/firefly/pull/804
> Fix status, org, and node parsing with latest core

- src/components/Lists/SubStatusList.tsx
- src/components/Slides/ListenerSlide.tsx
- src/components/Slides/SubscriptionSlide.tsx
- src/interfaces/api.ts
- src/interfaces/constants.ts
- src/translations/en.json
depends on https://github.com/hyperledger/firefly/pull/1028
> Add status sections to subscription & listener slides

- src/components/NetworkMap/NetworkMap.tsx
- src/pages/Network/views/Dashboard.tsx
back port of https://github.com/hyperledger/firefly-ui/pull/196
> [release-1.0]: update network map to better fit large networks

- src/pages/Tokens/views/Dashboard.tsx
> fix "Recent Token Transfers" pagination

- src/pages/Tokens/views/Transfers.tsx
> [tokenTransferTable] pagination fix

- src/pages/Tokens/views/Pools.tsx
> [remove-pool-datefilter]

- src/pages/Tokens/views/PoolDetails.tsx
> [tokenPool-details-bug]

- .github/workflows/build.yml
- .github/workflows/release.yml
The versions https://github.com/actions/setup-node and https://github.com/actions/checkout are outdated so update them
> Update versions actions/checkout and actions/setup-node
